### ISSUE TITLE
Can't run on python3.8.4

### ISSUE THREAD

**Issue by jjwon0** [sourcegraph/lsif-py#11]
I don't quite know which python version this starts happening but lsif-py doesn't run:

```
  File "./lsif-py", line 6, in <module>
    main()
  File "/home/jwon/lsif-py/lsif_indexer/script.py", line 13, in main
    index(args.workspace, f, args.verbose, args.exclude_content)
  File "/home/jwon/lsif-py/lsif_indexer/index.py", line 285, in index
    FileIndexer(
  File "/home/jwon/lsif-py/lsif_indexer/index.py", line 61, in index
    self._index(source)
  File "/home/jwon/lsif-py/lsif_indexer/index.py", line 80, in _index
    self._export_definition(name)
  File "/home/jwon/lsif-py/lsif_indexer/index.py", line 116, in _export_definition
    docstring = name.docstring
  File "/home/jwon/lsif-py/lsif_indexer/analysis.py", line 41, in docstring
    return self.definition.docstring(raw=True, fast=False)
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/api/classes.py", line 246, in docstring
    doc = self._get_docstring()
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/api/classes.py", line 257, in _get_docstring
    return self._name.py__doc__()
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/names.py", line 340, in py__doc__
    names = self.goto()
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/names.py", line 155, in goto
    module_names = goto_import(context, name)
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/imports.py", line 76, in goto_import
    _prepare_infer_import(module_context, tree_name)
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/imports.py", line 114, in _prepare_infer_import
    importer = Importer(module_context.inference_state, tuple(import_path),
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/imports.py", line 168, in __init__
    debug.speed('import %s %s' % (import_path, module_context))
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/context.py", line 210, in __repr__
    return '%s(%s)' % (self.__class__.__name__, self._value)
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/value/module.py", line 263, in __repr__
    self.__class__.__name__, self._string_name,
  File "/home/jwon/.pyenv/versions/lsif-py-3.8.4/lib/python3.8/site-packages/jedi/inference/value/module.py", line 125, in _string_name
    r = re.search(r'([^%s]*?)(%s__init__)?(\.pyi?|\.so)?$' % sep, self._path)
  File "/home/jwon/.pyenv/versions/3.8.4/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

I believe this is because in Jedi self._path starts referring to a Path object rather than a str/bytes one, so the regex fails.

**Comment by nejch** [comment]
Jedi needs an upgrade, yeah. I had a little hack to make it work: https://gitlab.com/nejch1/code-intelligence-demo/-/blob/master/.gitlab-ci.yml#L16-17. Other packages using Jedi have had the same issue.

We could open a small PR but merging the renovate PR would achieve the same (see "what to expect" in https://github.com/sourcegraph/lsif-py/pull/6), and might help this kind of stuff in the future combined with a small smoke test in this repo to see if specific dependency versions break lsif-py. @efritz does that make sense?

**Comment by efritz** [comment]
Sorry for the delay. We've been putting all of our effort into Go, TypeScript, Java, and C/C++ recently so this project has not gotten a lot of love.

Once we do pick up effort on precise code intelligence support for Python we may re-evaluate our choice of a parsing/name resolution library (or it could happen that we keep using Jedi).

If bumping a dependency version fixes this issue for you in the interim, merging a quick PR to unblock your workflow would be no issue.

**Comment by nejch** [comment]
@efritz maybe best to merge #6? It will give you automated PR's so people don't need to do this manually.

See below.
![image](https://user-images.githubusercontent.com/16777978/96331722-eed7f500-105f-11eb-80b5-fe4974b13905.png)

**Comment by DavidBraunLA** [comment]
Upgrading Jedi to 0.18 caused a new problem:

```
% ./lsif-py .                                                                      
Indexing file ./setup.py
Traceback (most recent call last):
  File "/Users/david/Documents/Projects/lsif-py/./lsif-py", line 6, in <module>
    main()
  File "/Users/david/Documents/Projects/lsif-py/lsif_indexer/script.py", line 13, in main
    index(args.workspace, f, args.verbose, args.exclude_content)
  File "/Users/david/Documents/Projects/lsif-py/lsif_indexer/index.py", line 285, in index
    FileIndexer(
  File "/Users/david/Documents/Projects/lsif-py/lsif_indexer/index.py", line 61, in index
    self._index(source)
  File "/Users/david/Documents/Projects/lsif-py/lsif_indexer/index.py", line 68, in _index
    self.names = get_names(source, self.filename)
  File "/Users/david/Documents/Projects/lsif-py/lsif_indexer/analysis.py", line 54, in get_names
    definitions = jedi.names(
AttributeError: module 'jedi' has no attribute 'names'
```

**Comment by macraig** [comment]
`lsif-py` is now considered deprecated, please use https://github.com/sourcegraph/scip-python instead.
