### ISSUE TITLE
KeyError when running lsif-py

### ISSUE THREAD

**Issue by wchau** [sourcegraph/lsif-py#20]
~/lsif-py/lsif-py .

Loading files (93.61s)
Generating LSIF data (93.61s)
Traceback (most recent call last):
  File "/Users/william.chau/lsif-py/lsif-py", line 6, in <module>
    lsif_py()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/william.chau/lsif-py/lsif_indexer/indexer.py", line 611, in lsif_py
    for element in project.index():
  File "/Users/william.chau/lsif-py/lsif_indexer/indexer.py", line 504, in index
    self.load_files()
  File "/Users/william.chau/lsif-py/lsif_indexer/indexer.py", line 580, in load_files
    document = Document(script=script)
  File "<string>", line 9, in __init__
  File "/Users/william.chau/lsif-py/lsif_indexer/indexer.py", line 331, in __post_init__
    self.definitions = self.script.get_names(
  File "/usr/local/lib/python3.10/site-packages/jedi/api/__init__.py", line 544, in get_names
    names = self._names(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jedi/api/__init__.py", line 558, in _names
    defs = [
  File "/usr/local/lib/python3.10/site-packages/jedi/api/__init__.py", line 559, in <listcomp>
    module_context.create_name(name)
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/context.py", line 294, in create_name
    func = self.create_value(funcdef)
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/context.py", line 236, in create_value
    func = value.FunctionValue.from_context(parent_context, node)
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/value/function.py", line 145, in from_context
    overloaded_funcs = list(_find_overload_functions(context, tree_node))
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/value/function.py", line 443, in _find_overload_functions
    filter = ParserTreeFilter(
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/filters.py", line 138, in __init__
    super().__init__(parent_context, node_context)
  File "/usr/local/lib/python3.10/site-packages/jedi/inference/filters.py", line 100, in __init__
    self._parso_cache_node = get_parso_cache_node(
  File "/usr/local/lib/python3.10/site-packages/jedi/parser_utils.py", line 287, in get_parso_cache_node
    return parser_cache[grammar._hashed][path]
KeyError: PosixPath(...)

**Comment by marquiswang** [comment]
I'm also observing this same error

```
Loading files (72.89s)
Generating LSIF data (72.89s)
Traceback (most recent call last):
  File "/Users/mwang/code/lsif-py/lsif-py", line 6, in <module>
    lsif_py()
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mwang/code/third-party/lsif-py/lsif_indexer/indexer.py", line 611, in lsif_py
    for element in project.index():
  File "/Users/mwang/code/third-party/lsif-py/lsif_indexer/indexer.py", line 504, in index
    self.load_files()
  File "/Users/mwang/code/third-party/lsif-py/lsif_indexer/indexer.py", line 580, in load_files
    document = Document(script=script)
  File "<string>", line 9, in __init__
  File "/Users/mwang/code/third-party/lsif-py/lsif_indexer/indexer.py", line 331, in __post_init__
    self.definitions = self.script.get_names(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/api/__init__.py", line 544, in get_names
    names = self._names(**kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/api/__init__.py", line 558, in _names
    defs = [
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/api/__init__.py", line 559, in <listcomp>
    module_context.create_name(name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 297, in create_name
    context = self.create_context(tree_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 288, in create_context
    return from_scope_node(scope_node, is_nested=True)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 258, in from_scope_node
    return self.create_value(scope_node).as_context()
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 236, in create_value
    func = value.FunctionValue.from_context(parent_context, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/function.py", line 145, in from_context
    overloaded_funcs = list(_find_overload_functions(context, tree_node))
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/function.py", line 447, in _find_overload_functions
    names = filter.get(tree_node.name.value)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/filters.py", line 109, in get
    return self._convert_names(self._filter(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/filters.py", line 145, in _filter
    return list(self._check_flows(names))
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/filters.py", line 156, in _check_flows
    check = flow_analysis.reachability_check(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/flow_analysis.py", line 85, in reachability_check
    return _break_check(context, value_scope, first_flow_scope, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/flow_analysis.py", line 100, in _break_check
    reachable = _check_if(context, flow_node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/flow_analysis.py", line 120, in _check_if
    types = context.infer_node(node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 208, in _infer_node
    value_set = infer_trailer(context, value_set, trailer)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 278, in infer_trailer
    return atom_values.execute(args)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 487, in execute
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 487, in <genexpr>
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 133, in wrapper
    return func(value, arguments=arguments, callback=call)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 158, in wrapper
    args = tuple(iterate_argument_clinic(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/arguments.py", line 94, in iterate_argument_clinic
    value_set = NO_VALUES if argument is None else argument.infer()
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/lazy_value.py", line 48, in infer
    return self.context.infer_node(self.data)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/pytest.py", line 74, in wrapper
    return func(param_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/names.py", line 528, in infer
    values = dynamic_param_lookup(self.function_value, param.position_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 47, in wrapper
    return func(function_value, param_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 92, in dynamic_param_lookup
    values = ValueSet.from_sets(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 93, in <genexpr>
    get_executed_param_names(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/param.py", line 28, in infer
    return self._lazy_value.infer()
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/lazy_value.py", line 48, in infer
    return self.context.infer_node(self.data)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/pytest.py", line 74, in wrapper
    return func(param_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/names.py", line 528, in infer
    values = dynamic_param_lookup(self.function_value, param.position_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 47, in wrapper
    return func(function_value, param_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 91, in dynamic_param_lookup
    arguments_list = _search_function_arguments(module_context, funcdef, string_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 139, in _search_function_arguments
    for arguments in _check_name_for_execution(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 197, in _check_name_for_execution
    for value in inference_state.infer(context, name):
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/__init__.py", line 180, in infer
    return helpers.infer_call_of_leaf(context, name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/helpers.py", line 104, in infer_call_of_leaf
    values = context.infer_node(base)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/pytest.py", line 74, in wrapper
    return func(param_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/names.py", line 528, in infer
    values = dynamic_param_lookup(self.function_value, param.position_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 47, in wrapper
    return func(function_value, param_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 91, in dynamic_param_lookup
    arguments_list = _search_function_arguments(module_context, funcdef, string_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 139, in _search_function_arguments
    for arguments in _check_name_for_execution(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 197, in _check_name_for_execution
    for value in inference_state.infer(context, name):
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/__init__.py", line 180, in infer
    return helpers.infer_call_of_leaf(context, name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/helpers.py", line 79, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 77, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/pytest.py", line 74, in wrapper
    return func(param_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/names.py", line 528, in infer
    values = dynamic_param_lookup(self.function_value, param.position_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 47, in wrapper
    return func(function_value, param_index)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 91, in dynamic_param_lookup
    arguments_list = _search_function_arguments(module_context, funcdef, string_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 139, in _search_function_arguments
    for arguments in _check_name_for_execution(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/dynamic_params.py", line 197, in _check_name_for_execution
    for value in inference_state.infer(context, name):
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/__init__.py", line 180, in infer
    return helpers.infer_call_of_leaf(context, name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/helpers.py", line 107, in infer_call_of_leaf
    values = infer_trailer(context, values, trailer)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 271, in infer_trailer
    return atom_values.py__getattribute__(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 496, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 496, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 84, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 84, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/instance.py", line 510, in infer
    return super().infer()
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/names.py", line 281, in infer
    return tree_name_to_values(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 867, in wrapper
    return func(inference_state, context, tree_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/django.py", line 177, in wrapper
    result = func(inference_state, context, tree_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 738, in tree_name_to_values
    types = infer_expr_stmt(context, node, tree_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 376, in infer_expr_stmt
    return _infer_expr_stmt(context, stmt, seek_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 409, in _infer_expr_stmt
    value_set = context.infer_node(rhs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 208, in _infer_node
    value_set = infer_trailer(context, value_set, trailer)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 278, in infer_trailer
    return atom_values.execute(args)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 487, in execute
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/base_value.py", line 487, in <genexpr>
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 134, in wrapper
    return call()
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 107, in call
    return callback(value, arguments=arguments)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/plugins/pytest.py", line 27, in wrapper
    return callback(value, arguments)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/__init__.py", line 119, in execute
    value_set = value.py__call__(arguments=arguments)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/klass.py", line 156, in py__call__
    if self.is_typeddict():
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/klass.py", line 284, in is_typeddict
    if method():
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/klass.py", line 273, in is_typeddict
    for cls in lazy_cls.infer():
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/lazy_value.py", line 48, in infer
    return self.context.infer_node(self.data)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 197, in _infer_node
    value_set = context.infer_node(first_child)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 45, in py__getattribute__
    names = self.goto(name_or_str, position)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 34, in goto
    names = finder.filter_name(filters, name_or_str)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/finder.py", line 35, in filter_name
    for filter in filters:
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 486, in get_global_filters
    yield from context.get_filters(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/context.py", line 318, in get_filters
    next(filters, None)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/value/module.py", line 63, in get_filters
    ParserTreeFilter(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/filters.py", line 138, in __init__
    super().__init__(parent_context, node_context)
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/inference/filters.py", line 100, in __init__
    self._parso_cache_node = get_parso_cache_node(
  File "/opt/homebrew/lib/python3.9/site-packages/jedi/parser_utils.py", line 287, in get_parso_cache_node
    return parser_cache[grammar._hashed][path]
KeyError: PosixPath('/opt/homebrew/lib/python3.9/site-packages/pandas/core/generic.py')
```

**Comment by nejch** [comment]
@marquiswang I don't think this project is really actively maintained - see https://github.com/sourcegraph/lsif-py/pull/17#pullrequestreview-823816588, though I haven't seen any activity around the other implementation mentioned in the other PR.

**Comment by macraig** [comment]
`lsif-py` is now considered deprecated, please use https://github.com/sourcegraph/scip-python instead.
