### ISSUE TITLE
LSIF-PY: Error in Upload and Code intel not able to link sub packages in a monorepo

### ISSUE THREAD

**Issue by northyg** [sourcegraph/lsif-py#26]
### Description

* SRC CLI version: 3.38.0
* Sourcegraph version: 136196_2022-03-10_bd60b4b0391c (we realize this is accidentally insiders for now, but mentioning in case it matters for this issue)
* Submitted from a customer with information redacted. [ticket link](https://sourcegraph.zendesk.com/agent/tickets/7154)

Reported that when trying to use LSIF-PY, they received an error (below) and code intelligence is not able to link sub 
packages in the monorepo. The error happened when running the lsif-py tool on the python codebases (and ran into this in every one of the python repos) Example:

![image](https://user-images.githubusercontent.com/27694443/161315714-519676f5-0b50-4a98-9461-2af00552d7ee.png)

> For example `@bfly/ui` resolves locally to `’../libraries/ui` but Souregraph is not seeing that The same is true for imports like in other repos, Sourcegraph seems to understand which dependencies are part of the graph (or is guessing) but not where to resolve them strictly. 

Stack trace with name info redacted:

```
% ./lsif-py /Users/redactedname/src/redacted-link/redacted-link
 
 
Loaded 58 files (3.47s)
 
Indexing (9.28s)
Generating LSIF data (12.76s)
Traceback (most recent call last):
  File "/Users/redactedname/src/lsif-py/./lsif-py", line 6, in <module>
    lsif_py()
  File "/Users/redactedname/.pyenv/versions/global/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/redactedname/.pyenv/versions/global/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/redactedname/.pyenv/versions/global/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/redactedname/.pyenv/versions/global/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 611, in lsif_py
    for element in project.index():
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 521, in index
    yield from self.toposort_index(to_index)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 562, in toposort_index
    yield from try_to_index(document)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 555, in try_to_index
    yield from try_to_index(dep)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 555, in try_to_index
    yield from try_to_index(dep)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 555, in try_to_index
    yield from try_to_index(dep)
  File "/Users/redactedname/src/lsif-py/lsif_indexer/indexer.py", line 553, in try_to_index
    raise CircularDependencyError(stack, dep.filename)
lsif_indexer.indexer.CircularDependencyError: Circular dependency detected: /Users/redactedname/src/redacted-link/redacted-link/dicom_client.py -> /Users/redactedname/src/redacted-link/redacted-link/dicom.py -> /Users/redactedname/src/redacted-link/redacted-link/utils/client.py -> /Users/redactedname/src/redacted-link/redacted-link/models.py -> /Users/redactedname/src/redacted-link/redacted-link/dicom.py
```

#### Questions:

1. What could be causing this error? Is the behavior described in the screen shot and behavior expected given that the Python LSIF Indexer status is 'in development'?
2. I had trouble figuring out if this is a potential compatibility issue with either Sourcegraph, SRC CLI, Python, etc. What would help me narrow this down in the future?

**Comment by northyg** [comment]
Closing because I was made aware that this [version is unstable](https://lsif.dev/) and there is a separate effort to re-work it.
